### ISSUE TITLE
$200: Need email verify mailer to send

### ISSUE THREAD

**Issue by kirkstrobeck** [tipfortip/issues#13]
This is an SSIM bounty, you must be an [official contributor](https://github.com/strobecksim/strobecksim.github.io/blob/master/Documents/Wiki/Index.md) to be compensated. 
<hr>

**Requirements:**

- Flow to support email verification processes like that required in https://github.com/tipfortip/issues/issues/14
- This is for any email address entered, wether confirming an accounts primary email or their PayPal email
- In the future a user may be able to add multiple emails
- We need a way to confirm that a user can receive email at ay email address they specify
- We may also need to confirm a users email that comes in thru their auth, ie. `Facebook`, because many people do not have an email they use regularly associated with their Facebook or other accounts.

**Comment by amoslanka** [comment]
Multiple emails and a confirmable paypal email are problems to deal with when we scale. I think there are other priorities to work on before those become major needs.

Meanwhile, confirmable accounts definitely needs to happen, especially since we sometimes get unconfirmed emails from Facebook auths. Our auth framework, Devise, provides an OOB tool for this, so it should be a quick addition to add confirmations. This effectively is a confirmation of the user, not of an individual email, though it uses their email account as the messaging tool. That should be easy to add to the system.

Sound like a plan?

**Comment by kirkstrobeck** [comment]
We can chat -- my main point is I don’t want to pay any email address that isn’t confirmed.

**Comment by kirkstrobeck** [comment]
Hey @amoslanka where are we on verify email?

**Comment by amoslanka** [comment]
Confirmations on server side is shipped.
